### ISSUE TITLE
Unable to use sendToken to transfer tokens in devnet environment

### ISSUE THREAD

**Issue by Adw8** [axelarnetwork/support#104]
Hello, I am trying to use the `sendToken` method from [Axelarjs-sdk](https://github.com/axelarnetwork/axelarjs-sdk) to send `aUSDC` tokens between chains. The code for doing this in a testnet environment is available [on the docs](https://docs.axelar.dev/dev/send-tokens/introduction#evm-chain-example). I have changed the environment from `Environment.TESTNET` to `Environment.DEVNET`, and I am trying to do a token transfer from Avalanche Fuji to Ethereum-Sepolia. I am running into the following error.

Steps to reproduce
- Have `USDC` and `AVAX` tokens in your wallet
- Setup Node.js environment with Axelarjs dependancies
- Run the following code
```
const { AxelarAssetTransfer, CHAINS, Environment } = require("@axelar-network/axelarjs-sdk");

const { ethers } = require("ethers");

const { getEvmSigner } = require("./utils");

const api = new AxelarAssetTransfer({ environment: Environment.DEVNET });

// add values
const DESTINATION_ADDRESS = "";
const TOKEN = "aUSDC";
const AMOUNT = "100000";
const PRIVATE_KEY = "";

const test = async () => {
  const provider = new ethers.providers.JsonRpcProvider("https://avalanche-fuji-c-chain-rpc.publicnode.com/");
  const evmSigner = getEvmSigner(PRIVATE_KEY).connect(provider);
  const requestOptions = {
    fromChain: CHAINS.TESTNET.AVALANCHE,
    toChain: CHAINS.TESTNET.SEPOLIA,
    destinationAddress: DESTINATION_ADDRESS, 
    asset: { symbol: TOKEN },
    amountInAtomicUnits: AMOUNT,
    options: {
      evmOptions: {
        signer: evmSigner,
        provider,
        approveSendForMe: true,
      },
    },
  };
  console.log("Sending tokens...");
  console.log("address is", await evmSigner.getAddress());
  // console.log("balance is", await evmSigner.getBalance());
  return api.sendToken(requestOptions);
};

test().then((transaction) => {
  console.log(transaction);
});

```

Error:
```
adwait@vivobook-m1603qa:~/projects/ds-repos/axelar-dev/src$ node devnet-transfer.js 


Sending tokens...


/home/adwait/projects/ds-repos/axelar-dev/node_modules/@axelar-network/axelarjs-sdk/dist/src/utils/validateChain.js:46
                throw new Error(`Invalid chain identifier for ${chains[i]}. Did you mean ${validations[i].bestMatch}?`);
                      ^

Error: Invalid chain identifier for ethereum-sepolia. Did you mean ethereum?
    at /home/adwait/projects/ds-repos/axelar-dev/node_modules/@axelar-network/axelarjs-sdk/dist/src/utils/validateChain.js:46:23
    at Generator.next (<anonymous>)
    at fulfilled (/home/adwait/projects/ds-repos/axelar-dev/node_modules/@axelar-network/axelarjs-sdk/dist/src/utils/validateChain.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.20.1

```

From the [devnet-chain-config.json](https://axelar-testnet.s3.us-east-2.amazonaws.com/devnet-chain-config.json) map, It seems that the correct chain name is `ethereum`, not `ethereum-sepolia`. So, making the following change in the code: 

```
toChain: CHAINS.MAINNET.ETHEREUM,
```
yields the following error

```

/home/adwait/projects/ds-repos/axelar-dev/node_modules/@axelar-network/axelarjs-sdk/dist/src/libs/AxelarAssetTransfer.js:153
                throw new Error("cannot find chain" + fromChain);
                      ^

Error: cannot find chainAvalanche
    at AxelarAssetTransfer.<anonymous> (/home/adwait/projects/ds-repos/axelar-dev/node_modules/@axelar-network/axelarjs-sdk/dist/src/libs/AxelarAssetTransfer.js:153:23)
    at Generator.next (<anonymous>)
    at fulfilled (/home/adwait/projects/ds-repos/axelar-dev/node_modules/@axelar-network/axelarjs-sdk/dist/src/libs/AxelarAssetTransfer.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

```

Would appreciate if there are any inputs/suggestions, thanks!

**Comment by Olanetsoft** [comment]
Friendly bump here ^ @Adw8
