### ISSUE TITLE
Question about val startup failure

### ISSUE THREAD

**Issue by 99Kies** [axelarnetwork/support#111]
I ran into this problem when I followed this documentation to this point.
https://docs.axelar.dev/validator/setup/manual#check-logs

logs:
```
May 06 12:36:05 axelar-mainnet systemd[1]: Started Vald daemon.
May 06 12:36:05 axelar-mainnet sh[419904]: 2024-05-06T12:36:05Z INF start listening to events module=vald
May 06 12:36:05 axelar-mainnet sh[419904]: 2024-05-06T12:36:05Z INF initiate connection to tofnd gRPC server: localhost:50051 module=vald
May 06 12:36:05 axelar-mainnet sh[419904]: 2024-05-06T12:36:05Z DBG successful connection to tofnd gRPC server module=vald
May 06 12:36:05 axelar-mainnet sh[419904]: 2024-05-06T12:36:05Z ERR failed to create an RPC connection for EVM chain Ethereum. Verify your RPC config.: Post "http://127.0.0.1:7545": dial tcp 127.0.0.1:7545: connect: connection refused module=vald
May 06 12:36:05 axelar-mainnet sh[419904]: panic: failed to create an RPC connection for EVM chain Ethereum. Verify your RPC config.: Post "http://127.0.0.1:7545": dial tcp 127.0.0.1:7545: connect: connection refused
May 06 12:36:05 axelar-mainnet sh[419904]: goroutine 1 [running]:
May 06 12:36:05 axelar-mainnet sh[419904]: github.com/axelarnetwork/axelar-core/vald.createEVMMgr.func2({{0x218a47d, 0x8}, {0x21a179c, 0x15}, 0x1, 0x0, 0x0})
May 06 12:36:05 axelar-mainnet sh[419904]:         github.com/axelarnetwork/axelar-core/vald/start.go:483 +0x59e
May 06 12:36:05 axelar-mainnet sh[419904]: github.com/axelarnetwork/utils/slices.ForEach[...](...)
May 06 12:36:05 axelar-mainnet sh[419904]:         github.com/axelarnetwork/utils@v0.0.0-20230706045331-b7aacc1f4a2f/slices/slices.go:52
May 06 12:36:05 axelar-mainnet sh[419904]: github.com/axelarnetwork/axelar-core/vald.createEVMMgr({{{0x218b8ba, 0x9}, {0x21857b2, 0x5}, 0x37e11d600}, {0x3, 0x12a05f200, 0x4a817c800, {0x0, 0x0, ...}}, ...}, ...)
May 06 12:36:05 axelar-mainnet sh[419904]:         github.com/axelarnetwork/axelar-core/vald/start.go:467 +0x154
May 06 12:36:05 axelar-mainnet sh[419904]: github.com/axelarnetwork/axelar-core/vald.listen({{0xc001170b58, 0x14, 0x18}, {0x304a1c8, 0xc001004990}, {0x7ffff196aebc, 0xd}, {0x302cb28, 0xc0004b74d0}, {0x303ee20, ...}, ...}, ...)
May 06 12:36:05 axelar-mainnet sh[419904]:         github.com/axelarnetwork/axelar-core/vald/start.go:205 +0x6a5
May 06 12:36:05 axelar-mainnet sh[419904]: github.com/axelarnetwork/axelar-core/vald.runVald({{0xc001170b58, 0x14, 0x18}, {0x304a1c8, 0xc001004990}, {0x7ffff196aebc, 0xd}, {0x302cb28, 0xc0004b74d0}, {0x303ee20, ...}, ...}, ...)
May 06 12:36:05 axelar-mainnet sh[419904]:         github.com/axelarnetwork/axelar-core/vald/start.go:158 +0x69a
May 06 12:36:05 axelar-mainnet sh[419904]: github.com/axelarnetwork/axelar-core/vald.GetValdCommand.func2(0xc000fb0d00?, {0xc001006280?, 0x0?, 0x8?})
May 06 12:36:05 axelar-mainnet sh[419904]:         github.com/axelarnetwork/axelar-core/vald/start.go:99 +0x425
May 06 12:36:05 axelar-mainnet sh[419904]: github.com/spf13/cobra.(*Command).execute(0xc000f96300, {0xc001006200, 0x8, 0x8})
May 06 12:36:05 axelar-mainnet sh[419904]:         github.com/spf13/cobra@v1.7.0/command.go:940 +0x87c
May 06 12:36:05 axelar-mainnet sh[419904]: github.com/spf13/cobra.(*Command).ExecuteC(0xc0004e6600)
May 06 12:36:05 axelar-mainnet sh[419904]:         github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5
May 06 12:36:05 axelar-mainnet sh[419904]: github.com/spf13/cobra.(*Command).Execute(...)
May 06 12:36:05 axelar-mainnet sh[419904]:         github.com/spf13/cobra@v1.7.0/command.go:992
May 06 12:36:05 axelar-mainnet sh[419904]: github.com/spf13/cobra.(*Command).ExecuteContext(...)
May 06 12:36:05 axelar-mainnet sh[419904]:         github.com/spf13/cobra@v1.7.0/command.go:985
May 06 12:36:05 axelar-mainnet sh[419904]: github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x2186964?, {0xc000021a40, 0x14})
May 06 12:36:05 axelar-mainnet sh[419904]:         github.com/cosmos/cosmos-sdk@v0.45.16/server/cmd/execute.go:36 +0x167
May 06 12:36:05 axelar-mainnet sh[419904]: main.main()
May 06 12:36:05 axelar-mainnet sh[419904]:         github.com/axelarnetwork/axelar-core/cmd/axelard/main.go:73 +0x48f
May 06 12:36:05 axelar-mainnet systemd[1]: vald.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
May 06 12:36:05 axelar-mainnet systemd[1]: vald.service: Failed with result 'exit-code'.
```

**Comment by 99Kies** [comment]
It seems to be because I didn't add any rpc information for the external chain, I added it now and after restarting I don't get the error message above.
https://docs.axelar.dev/validator/external-chains/overview

**Comment by 99Kies** [comment]
@Olanetsoft Hi, I'm preparing for the creation of a validator, how should I check the status of tofnd and vald. will tofnd and vald cause my validator to be slashed afterwards?

**Comment by Olanetsoft** [comment]
Its shouldn't cause it to slash, i believe. To check the status, take a look at this doc: https://docs.axelar.dev/validator/troubleshoot/startup

Let me know if that helps.
