### ISSUE TITLE
The testnet interchain interface throws when inputting a custom ERC-20 token address

### ISSUE THREAD

**Issue by 0xsha** [axelarnetwork/support#115]
Steps : 
1-  go to https://testnet.interchain.axelar.dev and input a custom ERC-20 address 
2- visit https://testnet.interchain.axelar.dev/ethereum-sepolia/0xVALIDERC20ADDRESS
3- crash 

```
{
  "message": "Cannot read properties of undefined (reading 'toLowerCase')",
  "stack": [
    "TypeError: Cannot read properties of undefined (reading 'toLowerCase')",
    "    at https://testnet.interchain.axelar.dev/_next/static/chunks/61-748b278e5b748bd8.js:1:7644",
    "    at Array.find (<anonymous>)",
    "    at https://testnet.interchain.axelar.dev/_next/static/chunks/61-748b278e5b748bd8.js:1:7602",
    "    at https://testnet.interchain.axelar.dev/_next/static/chunks/pages/_app-48fe23bc22a1f2a5.js:96:1658",
    "    at S (https://testnet.interchain.axelar.dev/_next/static/chunks/638.587db612aca7f0fd.js:1:6590)",
    "    at lk (https://testnet.interchain.axelar.dev/_next/static/chunks/framework-63c261f7457c35c5.js:25:60903)",
    "    at i (https://testnet.interchain.axelar.dev/_next/static/chunks/framework-63c261f7457c35c5.js:25:119420)",
    "    at uD (https://testnet.interchain.axelar.dev/_next/static/chunks/framework-63c261f7457c35c5.js:25:99073)",
    "    at https://testnet.interchain.axelar.dev/_next/static/chunks/framework-63c261f7457c35c5.js:25:98940",
    "    at uI (https://testnet.interchain.axelar.dev/_next/static/chunks/framework-63c261f7457c35c5.js:25:98947)",
    "    at uE (https://testnet.interchain.axelar.dev/_next/static/chunks/framework-63c261f7457c35c5.js:25:95699)",
    "    at uT (https://testnet.interchain.axelar.dev/_next/static/chunks/framework-63c261f7457c35c5.js:25:96088)",
    "    at r6 (https://testnet.interchain.axelar.dev/_next/static/chunks/framework-63c261f7457c35c5.js:25:44813)",
    "    at https://testnet.interchain.axelar.dev/_next/static/chunks/framework-63c261f7457c35c5.js:25:93599"
  ],
  "cause": {
    "name": "React ErrorBoundary TypeError"
  },
  "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36",
  "url": "https://testnet.interchain.axelar.dev/ethereum-sepolia/0xVALIDERC20ADDRESS",
  "locale": "en-US",
  "isRTL": false
}
```

**Comment by Olanetsoft** [comment]
This is now fixed. Kindly let us know if you are experiencing any other issues. Thank you
