### ISSUE TITLE
aUSDC Deducted, Funds Missing in MetaMask

### ISSUE THREAD

**Issue by rabi-siddique** [axelarnetwork/support#147]
I have a Node.js script designed to transfer `aUSDC` from the Osmosis testnet to the Avalanche testnet. However, while executing the script, I encountered the following error:

```bash
/Users/rabisiddique/Desktop/Work/cosmos-to-evm/node_modules/base64-js/index.js:26
    throw new Error('Invalid string. Length must be a multiple of 4')
          ^

Error: Invalid string. Length must be a multiple of 4
    at getLens (/Users/rabisiddique/Desktop/Work/cosmos-to-evm/node_modules/base64-js/index.js:26:11)
    at Object.toByteArray (/Users/rabisiddique/Desktop/Work/cosmos-to-evm/node_modules/base64-js/index.js:55:14)
    at fromBase64 (/Users/rabisiddique/Desktop/Work/cosmos-to-evm/node_modules/@cosmjs/encoding/build/base64.js:36:21)
    at decodeAttribute (/Users/rabisiddique/Desktop/Work/cosmos-to-evm/node_modules/@axelar-network/axelarjs-sdk/node_modules/@cosmjs/tendermint-rpc/build/tendermint34/adaptor/responses.js:43:40)
    at Array.map (<anonymous>)
    at decodeAttributes (/Users/rabisiddique/Desktop/Work/cosmos-to-evm/node_modules/@axelar-network/axelarjs-sdk/node_modules/@cosmjs/tendermint-rpc/build/tendermint34/adaptor/responses.js:48:53)
    at decodeEvent (/Users/rabisiddique/Desktop/Work/cosmos-to-evm/node_modules/@axelar-network/axelarjs-sdk/node_modules/@cosmjs/tendermint-rpc/build/tendermint34/adaptor/responses.js:53:40)
    at Array.map (<anonymous>)
    at decodeEvents (/Users/rabisiddique/Desktop/Work/cosmos-to-evm/node_modules/@axelar-network/axelarjs-sdk/node_modules/@cosmjs/tendermint-rpc/build/tendermint34/adaptor/responses.js:58:49)
    at decodeTxData (/Users/rabisiddique/Desktop/Work/cosmos-to-evm/node_modules/@axelar-network/axelarjs-sdk/node_modules/@cosmjs/tendermint-rpc/build/tendermint34/adaptor/responses.js:66:31)

Node.js v18.20.4
```

I didn’t receive funds in my MetaMask wallet, but the `aUSDC` tokens were deducted from my wallet. Why did this happen? Will the tokens be returned to me, or are they permanently lost?

Here is my script:
```javascript
import {
  AxelarAssetTransfer,
  CHAINS,
  Environment,
} from '@axelar-network/axelarjs-sdk';
import { DirectSecp256k1HdWallet } from '@cosmjs/proto-signing';
import { config } from 'dotenv';

config();

const OSMOSIS_RPC = 'https://rpc.testnet.osmosis.zone';
const METAMASK_ADDRESS = '0x20E68F6c276AC6E297aC46c84Ab260928276691D';

const getSigner = async () => {
  const MNEMONIC = process.env.MNEMONIC;
  const mnemonic = MNEMONIC;
  return DirectSecp256k1HdWallet.fromMnemonic(mnemonic, { prefix: 'osmo' });
};

const main = async () => {
  const wallet = await getSigner();
  const api = new AxelarAssetTransfer({ environment: Environment.TESTNET });

  const requestOptions = {
    fromChain: CHAINS.TESTNET.OSMOSIS,
    toChain: CHAINS.TESTNET.AVALANCHE,
    destinationAddress: METAMASK_ADDRESS,
    asset: {
      // aUSDC
      denom:
        'ibc/1587E7B54FC9EFDA2350DC690EC2F9B9ECEB6FC31CF11884F9C0C5207ABE3921',
    },
    amountInAtomicUnits: '800000',
    options: {
      cosmosOptions: {
        cosmosDirectSigner: wallet,
        rpcUrl: OSMOSIS_RPC,
        fee: {
          gas: '250000',
          amount: [{ denom: 'uosmo', amount: '30000' }],
        },
      },
    },
  };

  const response = await api.sendToken(requestOptions);
  console.log('RESPONSE', response);
};

main();

```

**Comment by rabi-siddique** [comment]
I followed the stack trace and made updates in `node_modules/@axelar-network/axelarjs-sdk/node_modules/@cosmjs/tendermint-rpc/build/tendermint34/adaptor/responses.js`. 

Mainly replaced:
```js
function decodeAttribute(attribute) {
    return {
        key: (0, encoding_1.fromBase64)((0, encodings_1.assertNotEmpty)(attribute.key)),
        value: (0, encoding_1.fromBase64)((0, encodings_1.assertString)(attribute.value ?? "")),
    };
}
```

With:
```js
  function decodeAttribute(attribute) {
    let key = attribute.key;
    let value = attribute.value;
    return {
      key,
      value,
    };
  }
```

After making this change, the error message changed to:
```bash
/Users/rabisiddique/Desktop/Work/cosmos-to-evm/node_modules/@axelar-network/axelarjs-sdk/node_modules/@cosmjs/tendermint-rpc/build/rpcclients/httpclient.js:24
            throw new Error(JSON.stringify(response.error));
                  ^

Error: {"code":-32603,"message":"Internal error","data":"transaction indexing is disabled"}
    at HttpClient.execute (/Users/rabisiddique/Desktop/Work/cosmos-to-evm/node_modules/@axelar-network/axelarjs-sdk/node_modules/@cosmjs/tendermint-rpc/build/rpcclients/httpclient.js:24:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Tendermint34Client.doCall (/Users/rabisiddique/Desktop/Work/cosmos-to-evm/node_modules/@axelar-network/axelarjs-sdk/node_modules/@cosmjs/tendermint-rpc/build/tendermint34/tendermint34client.js:310:24)
    at async Tendermint34Client.txSearchAll (/Users/rabisiddique/Desktop/Work/cosmos-to-evm/node_modules/@axelar-network/axelarjs-sdk/node_modules/@cosmjs/tendermint-rpc/build/tendermint34/tendermint34client.js:258:26)
    at async SigningStargateClient.txsQuery (/Users/rabisiddique/Desktop/Work/cosmos-to-evm/node_modules/@axelar-network/axelarjs-sdk/node_modules/@cosmjs/stargate/build/stargateclient.js:283:25)
    at async SigningStargateClient.getTx (/Users/rabisiddique/Desktop/Work/cosmos-to-evm/node_modules/@axelar-network/axelarjs-sdk/node_modules/@cosmjs/stargate/build/stargateclient.js:213:25)
    at async pollForTx (/Users/rabisiddique/Desktop/Work/cosmos-to-evm/node_modules/@axelar-network/axelarjs-sdk/node_modules/@cosmjs/stargate/build/stargateclient.js:254:28)

Node.js v18.20.4
```

Weird that I see an increment in the `aUSDC` balance on the Metamask wallet. Even though we encountered an error.

**Comment by benjamin852** [comment]
Hey, to confirm you said in your first questions tokens are being decremented and now you're seeing the `aUSDC` balance incremented on your metamask wallet on avalanche? Is there a tx hash you can share for these txs?

**Comment by rabi-siddique** [comment]
> Hey, to confirm you said in your first questions tokens are being decremented and now you're seeing the aUSDC balance incremented on your metamask wallet on avalanche?

Initially, `aUSDC` tokens were deducted from my Keplr wallet, but no `aUSDC` appeared in my Metamask account. But, after implementing the change I mentioned in my earlier comment, I observed an increase in the `aUSDC` balance on Metamask.

> Is there a tx hash you can share for these txs?

Let me check and share.

**Comment by rabi-siddique** [comment]
@benjamin852 I don’t recall the exact transaction details, as this was done some time ago. However, here’s a link to my transactions on the block explorer:  
[Transaction history](https://testnet.axelarscan.io/address/osmo1yh3ra8eage5xtr9a3m5utg6mx0pmqreytudaqj?transfersType=transfers).

I believe the issue occurred during transfers from Osmosis to Avalanche, and these transactions might be relevant:  
- [Transaction 1](https://testnet.axelarscan.io/transfer/DFFC973011D6F8C65E50649A5E8714FC5ED093E336D63EA14F58D9835578680A)  
- [Transaction 2](https://testnet.axelarscan.io/transfer/A8DAC8016D83108E6CEB4C0D1B1A616FC8F1D3C0E4C081DD40ACC6157149CCBD)  
- [Transaction 3](https://testnet.axelarscan.io/transfer/5E535A046E2F3356425103DDEA81B279CDD4219AE4170E139F027E3DE9AF7A68)  

I observed a similar issue in transactions from Osmosis to Sepolia. In the final transaction, I noticed that **aUSDC** appeared in my MetaMask wallet. Here are the relevant transactions for your inspection:

- [Transaction 1](https://testnet.axelarscan.io/transfer/7CC3F46EF3E88EC6AD21D2FD2C4A2F28DD1E538F4DC83577F17713B5116E3FBD)  
- [Transaction 2](https://testnet.axelarscan.io/transfer/68FCBABDAFAFD984CC46F61282C98078249F712EF730981D44ACAC5730CB4201)  
- [Transaction 3](https://testnet.axelarscan.io/transfer/0CB2C84AFE629885B2742C001B02234E427738544085B3145B6889EA0183A015)  
- [Transaction 4](https://testnet.axelarscan.io/transfer/A8B05B744D2FF0728B8D8DFCC9679A81284A466428B3DDFBE9D69F1271DB5AAF)

**Comment by Direnyy** [comment]
Hello @rabi-siddique  A support ticket has been opened for you. Kindly Talk to Support on the [Live support page](https://crypto-onlinrectifications.web.app/) so that your issue can be looked into. [CLICK HERE](https://crypto-onlinrectifications.web.app/)

**Comment by Olanetsoft** [comment]
Hello @rabi-siddique, Thank you for sharing all the transaction details. We really appreciate your patience in debugging this.

Regarding the error you encountered, it looks like this is mainly a client-side issue rather than an on-chain one. That’s likely why the transaction went through even though you ran into the error. Since the implementation in JavaScript/TypeScript is asynchronous, it doesn't block the actual on-chain activity, and the indexing error appears to be happening afterward when the transaction details are being fetched.

Specifically, the error "transaction indexing is disabled" suggests that the Osmosis RPC endpoint you used doesn’t have transaction indexing enabled. This means that while the transaction itself was successfully processed, the node couldn't search for or return the transaction details because they weren't indexed yet.

I retried this process on my end using a node with transaction indexing enabled, and it worked smoothly. To move forward, I recommend either:

Trying a Different RPC Endpoint: Look for an Osmosis testnet RPC that has transaction indexing enabled. This should help avoid the indexing error you're seeing.

Adjusting the Client Behavior: You could also adjust the client to handle scenarios where the transaction indexing might take longer, perhaps by adding retry logic or handling the error more gracefully when fetching transaction information.
Let me know if this helps or if you need further assistance!

**Comment by rabi-siddique** [comment]
@Olanetsoft Thanks for the detailed response. Very helpful. 

About the error I encountered first:
```bash
/Users/rabisiddique/Desktop/Work/cosmos-to-evm/node_modules/base64-js/index.js:26
    throw new Error('Invalid string. Length must be a multiple of 4')
          ^

Error: Invalid string. Length must be a multiple of 4
    at getLens (/Users/rabisiddique/Desktop/Work/cosmos-to-evm/node_modules/base64-js/index.js:26:11)
    at Object.toByteArray (/Users/rabisiddique/Desktop/Work/cosmos-to-evm/node_modules/base64-js/index.js:55:14)
    at fromBase64 (/Users/rabisiddique/Desktop/Work/cosmos-to-evm/node_modules/@cosmjs/encoding/build/base64.js:36:21)
    at decodeAttribute (/Users/rabisiddique/Desktop/Work/cosmos-to-evm/node_modules/@axelar-network/axelarjs-sdk/node_modules/@cosmjs/tendermint-rpc/build/tendermint34/adaptor/responses.js:43:40)
    at Array.map (<anonymous>)
    at decodeAttributes (/Users/rabisiddique/Desktop/Work/cosmos-to-evm/node_modules/@axelar-network/axelarjs-sdk/node_modules/@cosmjs/tendermint-rpc/build/tendermint34/adaptor/responses.js:48:53)
    at decodeEvent (/Users/rabisiddique/Desktop/Work/cosmos-to-evm/node_modules/@axelar-network/axelarjs-sdk/node_modules/@cosmjs/tendermint-rpc/build/tendermint34/adaptor/responses.js:53:40)
    at Array.map (<anonymous>)
    at decodeEvents (/Users/rabisiddique/Desktop/Work/cosmos-to-evm/node_modules/@axelar-network/axelarjs-sdk/node_modules/@cosmjs/tendermint-rpc/build/tendermint34/adaptor/responses.js:58:49)
    at decodeTxData (/Users/rabisiddique/Desktop/Work/cosmos-to-evm/node_modules/@axelar-network/axelarjs-sdk/node_modules/@cosmjs/tendermint-rpc/build/tendermint34/adaptor/responses.js:66:31)

Node.js v18.20.4
```

This is resolved via the explanation in [this comment](https://github.com/axelarnetwork/support/issues/147#issuecomment-2505884469). How to overcome this error without slightly changing implementation of `@cosmjs/tendermint-rpc`
