### ISSUE TITLE
Error with task execution "Mint a new Interchain Token at http://interchain.axelar.dev"

### ISSUE THREAD

**Issue by Utah8O** [axelarnetwork/support#67]
Please advise me, I am doing everything as mentioned in this guide. https://twitter.com/axelarnetwork/status/1754919832691278330
I choose BNB-Chain.
Decimals 1.
Enter Total Supply 5000000. In the video it says this value with a comma, 5,000,000.
But I can't put commas in, so I put in this value 5000000.
I ran into a problem in step 3. 
I'm also attaching the error below. 
SyntaxError: Cannot convert 0,00000000000000000000 to a BigInt
    at BigInt (<anonymous>)
    at a (https://interchain.axelar.dev/_next/static/chunks/354-a8661048522703ca.js:1:83053)
    at https://interchain.axelar.dev/_next/static/chunks/563.d372c9ce416da0a0.js:1:6672
    at Object.lQ [as useMemo] (https://interchain.axelar.dev/_next/static/chunks/framework-63c261f7457c35c5.js:25:65276)
    at t.useMemo (https://interchain.axelar.dev/_next/static/chunks/framework-63c261f7457c35c5.js:41:5984)
    at E (https://interchain.axelar.dev/_next/static/chunks/563.d372c9ce416da0a0.js:1:6626)
    at lk (https://interchain.axelar.dev/_next/static/chunks/framework-63c261f7457c35c5.js:25:60903)
    at op (https://interchain.axelar.dev/_next/static/chunks/framework-63c261f7457c35c5.js:25:72785)
    at i (https://interchain.axelar.dev/_next/static/chunks/framework-63c261f7457c35c5.js:25:120317)
    at uD (https://interchain.axelar.dev/_next/static/chunks/framework-63c261f7457c35c5.js:25:99073)
    at https://interchain.axelar.dev/_next/static/chunks/framework-63c261f7457c35c5.js:25:98940
    at uI (https://interchain.axelar.dev/_next/static/chunks/framework-63c261f7457c35c5.js:25:98947)
    at uE (https://interchain.axelar.dev/_next/static/chunks/framework-63c261f7457c35c5.js:25:95699)
    at ux (https://interchain.axelar.dev/_next/static/chunks/framework-63c261f7457c35c5.js:25:94254)
    at x (https://interchain.axelar.dev/_next/static/chunks/framework-63c261f7457c35c5.js:49:1364)
    at MessagePort.R (https://interchain.axelar.dev/_next/static/chunks/framework-63c261f7457c35c5.js:49:1894)

I have tried changing browser, clearing cookies but it doesn't help.
![Axelar Error](https://github.com/axelarnetwork/support/assets/147143937/feca7bed-deca-407d-94da-3cd773ed4f9b)

**Comment by benjamin852** [comment]
Hey, I am trying to replicate error but unable to. Are you deploying on any other chains or just BNB? I was just able to deploy on BNB with 1 decimal 5mil total supply (no commas). Is your mintable? Please let me know exactly what your inputting so I can try replicate on my end thanks.

**Comment by Utah8O** [comment]
I attach screenshots below where I did everything step by step.
And I'm interested in the question, what's that address in the "Salt" string ?
![Axelar1](https://github.com/axelarnetwork/support/assets/147143937/0f128e96-805f-46ad-a377-3141cca22433)
![Axelar2](https://github.com/axelarnetwork/support/assets/147143937/f25372c2-b155-4e28-aca9-2a608f5914f1)
![Axelar3](https://github.com/axelarnetwork/support/assets/147143937/3c6bb0b8-c7ee-47f2-adcf-d4160e46862e)

**Comment by benjamin852** [comment]
The salt is a unique identifier for deploying the token.  So this is your unique salt which will be used for deployments across different chains to help keep the token deployment consistent across different chains (i.e. same address, same interchainTokenId)

As for your bug it looks like you're going through the portal correctly. Can you try again and this time check your console let me know if there are any helpful error messages popping up there. Also just confirming you have enough gas to cover the cost of the transaction? Also which browser are you using? Just want to see if I can replicate this error myself.

Thanks!

**Comment by Utah8O** [comment]
I'm attaching screenshots below.
I am using Chrome browser.
Which network should be on the gas payment? 
![Screenshot_1](https://github.com/axelarnetwork/support/assets/147143937/8d58ad26-4b12-41f0-8198-e367f84f6f70)
![Screenshot_2](https://github.com/axelarnetwork/support/assets/147143937/cca5106a-16e1-4351-a9f8-6f423575e8ed)
![Screenshot_3](https://github.com/axelarnetwork/support/assets/147143937/90bed4ce-33a9-4f37-a76a-e20aa2c9c827)

**Comment by benjamin852** [comment]
The gas is paid on whatever the source chain is that you're on, in this case it seems like you're on ethereum so just make sure you have funds on ethereum. I see you're on mainnet right now can you try https://testnet.interchain.axelar.dev/ just to see if it works on testnet for you there? Thanks

**Comment by Utah8O** [comment]
So I should choose some test network to try ?

**Comment by benjamin852** [comment]
Yes, make sure your wallet is funded with some native testnet token then deploy from that testnet chain, and let me know if that works.

**Comment by Utah8O** [comment]
Could you please tell me which test network to connect ? 
I've been trying to hook up Goerli
![Screenshot_1](https://github.com/axelarnetwork/support/assets/147143937/a351d4d5-08b8-4485-8e87-de08387c2e91)

**Comment by benjamin852** [comment]
Hey yes the Goerli chain has limited support as its being deprecated by the broader Ethereum community. Feel free to try any other EVM chain (Sepolia, Polygon Mumbai, Fantom, Avalanche etc.)

**Comment by Utah8O** [comment]
I understand that test networks cannot be connected or am I wrong ? 
Which one should I choose from the available ones, please ?
![Uploading Screenshot_1.png…]()

**Comment by arabzonov** [comment]
Same problem. Any solution?

**Comment by Utah8O** [comment]
> Same problem. Any solution?

still in process, buddy.

**Comment by benjamin852** [comment]
Test networks do work you're on the wrong portal though, based on your screenshot you're on the mainnet portal not testnet.

Mainnet: https://beta.interchain.axelar.dev/
Testnet: https://testnet.interchain.axelar.dev/

Make sure you're on the second link then try connect with testnet. Thanks!

**Comment by Utah8O** [comment]
I followed this link https://testnet.interchain.axelar.dev/ and tried the same steps on the Sepolia network. I'm attaching a screenshot.
![Screenshot_1](https://github.com/axelarnetwork/support/assets/147143937/40b9d071-1d1b-4d03-9181-2cc0c787259f)

**Comment by Utah8O** [comment]
I am also attaching the error code.
SyntaxError: Cannot convert 0,00000000000000000000 to a BigInt
    at BigInt (<anonymous>)
    at a (https://testnet.interchain.axelar.dev/_next/static/chunks/354-a8661048522703ca.js:1:83053)
    at https://testnet.interchain.axelar.dev/_next/static/chunks/563.9116dbe04692ad9b.js:1:6672
    at Object.lQ [as useMemo] (https://testnet.interchain.axelar.dev/_next/static/chunks/framework-63c261f7457c35c5.js:25:65276)
    at t.useMemo (https://testnet.interchain.axelar.dev/_next/static/chunks/framework-63c261f7457c35c5.js:41:5984)
    at E (https://testnet.interchain.axelar.dev/_next/static/chunks/563.9116dbe04692ad9b.js:1:6626)
    at lk (https://testnet.interchain.axelar.dev/_next/static/chunks/framework-63c261f7457c35c5.js:25:60903)
    at op (https://testnet.interchain.axelar.dev/_next/static/chunks/framework-63c261f7457c35c5.js:25:72785)
    at i (https://testnet.interchain.axelar.dev/_next/static/chunks/framework-63c261f7457c35c5.js:25:120317)
    at uD (https://testnet.interchain.axelar.dev/_next/static/chunks/framework-63c261f7457c35c5.js:25:99073)
    at https://testnet.interchain.axelar.dev/_next/static/chunks/framework-63c261f7457c35c5.js:25:98940
    at uI (https://testnet.interchain.axelar.dev/_next/static/chunks/framework-63c261f7457c35c5.js:25:98947)
    at uE (https://testnet.interchain.axelar.dev/_next/static/chunks/framework-63c261f7457c35c5.js:25:95699)
    at ux (https://testnet.interchain.axelar.dev/_next/static/chunks/framework-63c261f7457c35c5.js:25:94254)
    at x (https://testnet.interchain.axelar.dev/_next/static/chunks/framework-63c261f7457c35c5.js:49:1364)
    at MessagePort.R (https://testnet.interchain.axelar.dev/_next/static/chunks/framework-63c261f7457c35c5.js:49:1894)

**Comment by benjamin852** [comment]
Interesting. Thank you. I am still trying to replicate the error here, just to confirm this is happening right after you click the Register & Deploy button? 

I.e. You never make it to this step?

<img width="615" alt="Screenshot 2024-02-12 at 3 12 49 PM" src="https://github.com/axelarnetwork/support/assets/13651771/e276b0bb-e4fa-4498-93bc-1f95c2d10d0f">

**Comment by Utah8O** [comment]
Yeah, I can't go to "Register & Deploy." 
I just tried it again. 
I'm using the Chrome browser. 
I am attaching screenshots below of the data I entered. 
![1](https://github.com/axelarnetwork/support/assets/147143937/134088cd-f31b-4bda-bb98-0d0f10f313fc)
![2](https://github.com/axelarnetwork/support/assets/147143937/0d642299-f7d9-47ed-97be-2247788a3b71)
![3](https://github.com/axelarnetwork/support/assets/147143937/bb8f8a11-296e-4b55-b610-4ef4127cf717)
![4](https://github.com/axelarnetwork/support/assets/147143937/9104c730-a44b-4271-b23a-ee61f922fb8d)
And the error code.
SyntaxError: Cannot convert 0,00000000000000000000 to a BigInt
    at BigInt (<anonymous>)
    at a (https://testnet.interchain.axelar.dev/_next/static/chunks/354-a8661048522703ca.js:1:83053)
    at https://testnet.interchain.axelar.dev/_next/static/chunks/563.48f423d67508a867.js:1:7036
    at Object.lQ [as useMemo] (https://testnet.interchain.axelar.dev/_next/static/chunks/framework-63c261f7457c35c5.js:25:65276)
    at t.useMemo (https://testnet.interchain.axelar.dev/_next/static/chunks/framework-63c261f7457c35c5.js:41:5984)
    at F (https://testnet.interchain.axelar.dev/_next/static/chunks/563.48f423d67508a867.js:1:6990)
    at lk (https://testnet.interchain.axelar.dev/_next/static/chunks/framework-63c261f7457c35c5.js:25:60903)
    at op (https://testnet.interchain.axelar.dev/_next/static/chunks/framework-63c261f7457c35c5.js:25:72785)
    at i (https://testnet.interchain.axelar.dev/_next/static/chunks/framework-63c261f7457c35c5.js:25:120317)
    at uD (https://testnet.interchain.axelar.dev/_next/static/chunks/framework-63c261f7457c35c5.js:25:99073)
    at https://testnet.interchain.axelar.dev/_next/static/chunks/framework-63c261f7457c35c5.js:25:98940
    at uI (https://testnet.interchain.axelar.dev/_next/static/chunks/framework-63c261f7457c35c5.js:25:98947)
    at uE (https://testnet.interchain.axelar.dev/_next/static/chunks/framework-63c261f7457c35c5.js:25:95699)
    at ux (https://testnet.interchain.axelar.dev/_next/static/chunks/framework-63c261f7457c35c5.js:25:94254)
    at x (https://testnet.interchain.axelar.dev/_next/static/chunks/framework-63c261f7457c35c5.js:49:1364)
    at MessagePort.R (https://testnet.interchain.axelar.dev/_next/static/chunks/framework-63c261f7457c35c5.js:49:1894)

**Comment by Utah8O** [comment]
> Interesting. Thank you. I am still trying to replicate the error here, just to confirm this is happening right after you click the Register & Deploy button?
> 
> I.e. You never make it to this step?
> 
> <img alt="Screenshot 2024-02-12 at 3 12 49 PM" width="615" src="https://private-user-images.githubusercontent.com/13651771/304211582-e276b0bb-e4fa-4498-93bc-1f95c2d10d0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4MTM4MzksIm5iZiI6MTcwNzgxMzUzOSwicGF0aCI6Ii8xMzY1MTc3MS8zMDQyMTE1ODItZTI3NmIwYmItZTRmYS00NDk4LTkzYmMtMWY5NWMyZDEwZDBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEzVDA4Mzg1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3NjczMmU1ZDZhN2M1OWI5MTkyNzQzNmM4MTY1Y2Y4OWQ2OTAxZWU0Njc2Nzk5ZmNkODQ0NjRlMmYwZDdiMGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XITFeVtwTx89DDjx7i-sQt2To0N7EoTBRK6yKF6EMsM">

Could you please tell me what data you entered in "Token details" and in "Token Settings"?

**Comment by canhtrinh** [comment]
@Utah8O what browser are you using and what version?

**Comment by Utah8O** [comment]
@canhtrinh 
![Screenshot_1](https://github.com/axelarnetwork/support/assets/147143937/c2ccfd4b-9d1c-4e1d-bf25-3d11135fac08)
I take it you're having the same problem?

**Comment by Utah8O** [comment]
@benjamin852 Could you please tell me what data you entered in "Token details" and in "Token Settings"?

**Comment by benjamin852** [comment]
I am inputting the exact same paramters as you

**Comment by Utah8O** [comment]
@benjamin852 So, what do I do? 
Everyone has this error.
I take it you won't be able to participate ?

**Comment by benjamin852** [comment]
Team is working on a fix for this. Will update when it is rolled out

**Comment by Utah8O** [comment]
Thanks so much, mate )

**Comment by Utah8O** [comment]
@benjamin852 
I tried it again in Mozilla browser, the error is different. 
I still entered the same data. 
![Screenshot_1](https://github.com/axelarnetwork/support/assets/147143937/dbd2e352-ae74-4bfc-a547-c8ecf1442a91)
![Screenshot_2](https://github.com/axelarnetwork/support/assets/147143937/a199d476-b4d5-4685-9933-7495ed539f00)
![Screenshot_3](https://github.com/axelarnetwork/support/assets/147143937/0a899973-be6e-4ed7-a7fe-75a718d16d8a)
![Screenshot_4](https://github.com/axelarnetwork/support/assets/147143937/58c994af-9673-4cb6-9c78-c76db6bda030)



```
{
  "message": "invalid BigInt syntax",
  "stack": [
    "a@https://testnet.interchain.axelar.dev/_next/static/chunks/354-a8661048522703ca.js:1:83053",
    "50563/F/Z<@https://testnet.interchain.axelar.dev/_next/static/chunks/563.48f423d67508a867.js:1:7036",
    "lQ@https://testnet.interchain.axelar.dev/_next/static/chunks/framework-63c261f7457c35c5.js:25:65276",
    "5578/t.useMemo@https://testnet.interchain.axelar.dev/_next/static/chunks/framework-63c261f7457c35c5.js:41:5984",
    "F@https://testnet.interchain.axelar.dev/_next/static/chunks/563.48f423d67508a867.js:1:6990",
    "lk@https://testnet.interchain.axelar.dev/_next/static/chunks/framework-63c261f7457c35c5.js:25:60903",
    "op@https://testnet.interchain.axelar.dev/_next/static/chunks/framework-63c261f7457c35c5.js:25:72785",
    "i@https://testnet.interchain.axelar.dev/_next/static/chunks/framework-63c261f7457c35c5.js:25:120317",
    "uD@https://testnet.interchain.axelar.dev/_next/static/chunks/framework-63c261f7457c35c5.js:25:99074",
    "35565/uI/<@https://testnet.interchain.axelar.dev/_next/static/chunks/framework-63c261f7457c35c5.js:25:98942",
    "uI@https://testnet.interchain.axelar.dev/_next/static/chunks/framework-63c261f7457c35c5.js:25:98947",
    "uE@https://testnet.interchain.axelar.dev/_next/static/chunks/framework-63c261f7457c35c5.js:25:95699",
    "ux@https://testnet.interchain.axelar.dev/_next/static/chunks/framework-63c261f7457c35c5.js:25:94254",
    "x@https://testnet.interchain.axelar.dev/_next/static/chunks/framework-63c261f7457c35c5.js:49:1365",
    "R@https://testnet.interchain.axelar.dev/_next/static/chunks/framework-63c261f7457c35c5.js:49:1894",
    ""
  ],
  "cause": {
    "name": "React ErrorBoundary SyntaxError",
    "stack": "\nF@https://testnet.interchain.axelar.dev/_next/static/chunks/563.48f423d67508a867.js:1:575\nd@https://testnet.interchain.axelar.dev/_next/static/chunks/pages/index-702a2084d49b79bc.js:20:1917\nsection\n34438/K/</r/s<@https://testnet.interchain.axelar.dev/_next/static/chunks/pages/_app-2b751a22cb00cb86.js:5701:132514\ndialog\n34438/K/</r/s<@https://testnet.interchain.axelar.dev/_next/static/chunks/pages/_app-2b751a22cb00cb86.js:5701:132514\neA@https://testnet.interchain.axelar.dev/_next/static/chunks/pages/_app-2b751a22cb00cb86.js:5707:28\nProvider@https://testnet.interchain.axelar.dev/_next/static/chunks/pages/_app-2b751a22cb00cb86.js:98:11824\n34438/eN<@https://testnet.interchain.axelar.dev/_next/static/chunks/pages/_app-2b751a22cb00cb86.js:5707:756\nN@https://testnet.interchain.axelar.dev/_next/static/chunks/970.97ddb72d35dcf6e0.js:1:7668\nh@https://testnet.interchain.axelar.dev/_next/static/chunks/970.97ddb72d35dcf6e0.js:1:4841\nProvider@https://testnet.interchain.axelar.dev/_next/static/chunks/pages/_app-2b751a22cb00cb86.js:98:11824\nm@https://testnet.interchain.axelar.dev/_next/static/chunks/970.97ddb72d35dcf6e0.js:1:5650\nd@https://testnet.interchain.axelar.dev/_next/static/chunks/pages/index-702a2084d49b79bc.js:20:1917\ndiv\ndiv\nsection\n34438/K/</r/s<@https://testnet.interchain.axelar.dev/_next/static/chunks/pages/_app-2b751a22cb00cb86.js:5701:132514\ndiv\n19250/n.Z<@https://testnet.interchain.axelar.dev/_next/static/chunks/250-dd53fb690dbe811f.js:1:10655\n_@https://testnet.interchain.axelar.dev/_next/static/chunks/pages/index-702a2084d49b79bc.js:1:632\nm@https://testnet.interchain.axelar.dev/_next/static/chunks/pages/_app-2b751a22cb00cb86.js:29:151794\ndiv\n34438/K/</r/s<@https://testnet.interchain.axelar.dev/_next/static/chunks/pages/_app-2b751a22cb00cb86.js:5701:132514\ndiv\n34438/K/</r/s<@https://testnet.interchain.axelar.dev/_next/static/chunks/pages/_app-2b751a22cb00cb86.js:5701:132514\n34438/ej<@https://testnet.interchain.axelar.dev/_next/static/chunks/pages/_app-2b751a22cb00cb86.js:5707:1423\ntp@https://testnet.interchain.axelar.dev/_next/static/chunks/pages/_app-2b751a22cb00cb86.js:54:34568\nProvider@https://testnet.interchain.axelar.dev/_next/static/chunks/pages/_app-2b751a22cb00cb86.js:98:11824\nProvider@https://testnet.interchain.axelar.dev/_next/static/chunks/pages/_app-2b751a22cb00cb86.js:98:11824\nProvider@https://testnet.interchain.axelar.dev/_next/static/chunks/pages/_app-2b751a22cb00cb86.js:98:11824\nMainLayout\nl@https://testnet.interchain.axelar.dev/_next/static/chunks/pages/_app-2b751a22cb00cb86.js:105:106669\n_@https://testnet.interchain.axelar.dev/_next/static/chunks/pages/_app-2b751a22cb00cb86.js:5701:55842\nb@https://testnet.interchain.axelar.dev/_next/static/chunks/pages/_app-2b751a22cb00cb86.js:29:133133\nProvider@https://testnet.interchain.axelar.dev/_next/static/chunks/pages/_app-2b751a22cb00cb86.js:98:11824\na@https://testnet.interchain.axelar.dev/_next/static/chunks/pages/_app-2b751a22cb00cb86.js:105:106021\n21413/t.SessionProvider@https://testnet.interchain.axelar.dev/_next/static/chunks/pages/_app-2b751a22cb00cb86.js:29:59136\nl@https://testnet.interchain.axelar.dev/_next/static/chunks/pages/_app-2b751a22cb00cb86.js:105:106669\n84380/I<@https://testnet.interchain.axelar.dev/_next/static/chunks/pages/_app-2b751a22cb00cb86.js:29:133635\na@https://testnet.interchain.axelar.dev/_next/static/chunks/pages/_app-2b751a22cb00cb86.js:105:106021\nl@https://testnet.interchain.axelar.dev/_next/static/chunks/pages/_app-2b751a22cb00cb86.js:105:106669\nProvider@https://testnet.interchain.axelar.dev/_next/static/chunks/pages/_app-2b751a22cb00cb86.js:29:113116\no@https://testnet.interchain.axelar.dev/_next/static/chunks/pages/_app-2b751a22cb00cb86.js:29:129444\np@https://testnet.interchain.axelar.dev/_next/static/chunks/main-d6b812eee35f1017.js:1:57270\n$@https://testnet.interchain.axelar.dev/_next/static/chunks/main-d6b812eee35f1017.js:1:8764\nQ@https://testnet.interchain.axelar.dev/_next/static/chunks/main-d6b812eee35f1017.js:1:10278\nel@https://testnet.interchain.axelar.dev/_next/static/chunks/main-d6b812eee35f1017.js:1:13510"
  },
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0",
  "url": "https://testnet.interchain.axelar.dev/",
  "locale": "ru-RU",
  "isRTL": false
}
```

**Comment by benjamin852** [comment]
Hey still looks like the same `BigInt` error to me, sorry for the delay here hoping team can get this sorted soon

**Comment by benjamin852** [comment]
Hi, @Utah8O  can you please try again see if this is working now? Thanks

**Comment by benjamin852** [comment]
I'm glad to hear it's working for you now! Sorry you missed the contest, I know the team works very hard to fix these as quickly as possible, and this bug was tricky as it was only popping up for some users. A lot of stuff on the team's plate when launching a new product on this scale.

**Comment by Utah8O** [comment]
@benjamin852 Thank you so much for your help) It's all good))))
