### ISSUE TITLE
I can't deploy an ITS Token

### ISSUE THREAD

**Issue by JLiBercry** [axelarnetwork/support#77]
I have a question, because I have tried everything and I can not deploy an ITS Token, I think the problem is my region because I live in Spain, can this be the problem? I can not go to step 3 but friends outside Spain if they can move forward, I do not know if it's my computer or what the problem is, can you help me, please? This is the error that comes out when I try, same error in different browsers and different wallets, I have created a new wallet and again the same error occurs, I do not know what to do anymore, I need help and many users have this same error, can you tell me what is happening? Please consider extending the ITS competition, it's not fair that most users can't deploy a token to participate.

This is the error when I go from step 2 to step 3, following the same steps like other users who can complete the deployment:

SyntaxError: Cannot convert 0,00000000000000000000 to a BigInt
    at BigInt (<anonymous>)
    at a (https://interchain.axelar.dev/_next/static/chunks/354-a8661048522703ca.js:1:83053)
    at https://interchain.axelar.dev/_next/static/chunks/563.287d068aee0916bd.js:1:7036
    at Object.lQ [as useMemo] (https://interchain.axelar.dev/_next/static/chunks/framework-63c261f7457c35c5.js:25:65276)
    at t.useMemo (https://interchain.axelar.dev/_next/static/chunks/framework-63c261f7457c35c5.js:41:5984)
    at F (https://interchain.axelar.dev/_next/static/chunks/563.287d068aee0916bd.js:1:6990)
    at lk (https://interchain.axelar.dev/_next/static/chunks/framework-63c261f7457c35c5.js:25:60903)
    at op (https://interchain.axelar.dev/_next/static/chunks/framework-63c261f7457c35c5.js:25:72785)
    at i (https://interchain.axelar.dev/_next/static/chunks/framework-63c261f7457c35c5.js:25:120317)
    at uD (https://interchain.axelar.dev/_next/static/chunks/framework-63c261f7457c35c5.js:25:99073)
    at https://interchain.axelar.dev/_next/static/chunks/framework-63c261f7457c35c5.js:25:98940
    at uI (https://interchain.axelar.dev/_next/static/chunks/framework-63c261f7457c35c5.js:25:98947)
    at uE (https://interchain.axelar.dev/_next/static/chunks/framework-63c261f7457c35c5.js:25:95699)
    at uT (https://interchain.axelar.dev/_next/static/chunks/framework-63c261f7457c35c5.js:25:96088)
    at r6 (https://interchain.axelar.dev/_next/static/chunks/framework-63c261f7457c35c5.js:25:44813)
    at https://interchain.axelar.dev/_next/static/chunks/framework-63c261f7457c35c5.js:25:93599

**Comment by canhtrinh** [comment]
@JLiBercry can you file a ticket here (https://axelar.zendesk.com/hc/en-us/requests/new) and tell me here what the ticket # is, once it's generated? 

i want to set up a troubleshoot with you tomorrow to discuss

**Comment by benjamin852** [comment]
Hey the team is looking into this we'll provide an update once bugfix is released. Thanks for flagging

**Comment by JLiBercry** [comment]
What about old wallets? this is my address I use, but I also try on a new
address too:

0x0A5960eE3D261A89F563B2FC105487bA30cAE475

**Comment by benjamin852** [comment]
Hey, I am sorry can you clarify what you mean by your old address? You're having the BigInt bug with a different address you mean? Thanks

**Comment by JLiBercry** [comment]
The address I use has more than 6 years. I don't know if is a problem

**Comment by benjamin852** [comment]
Hi, @JLiBercry can you please try again see if this is working now? Thanks

**Comment by benjamin852** [comment]
bug has been fixed should be working now please confirm if issue needs to be re-examined closing this issue unless i hear otherwise, thanks!
